### ISSUE TITLE
Support Deploy from Metadata API Source

### ISSUE THREAD

**Issue by dfruddffdc** [wadewegner/deploy-to-sfdx#19]
This is an enhancement request.

Can the tool be enhanced to deploy to a scratch org using source code in the Metadata API format? This would make it easier to add to existing repos, without introducing breaking changes for consumers who haven't yet adopted SFDX.

**Comment by wadewegner** [comment]
I'm going to experiment with this here: https://github.com/wadewegner/deploy-to-sfdx/issues/24
