### ISSUE TITLE
deployments.sql not up to date ?

### ISSUE THREAD

**Issue by FabienTaillon** [wadewegner/deploy-to-sfdx#27]
I tried to run deploy-to-sfdx locally following the local setup instructions, including executing `deployments.sql`.

However it doesn't work as it seems that some columns are missing on the `deployments` table (`guid`, `settings`), and table `deployment_steps` doesn't exists at all.

Maybe you have a more up to date `deployments.sql` version that wasn't pushed to the repo ?

**Comment by Stefanvdk** [comment]
When I tried to run this app locally I encountered this same issue. I found that on the deployments table next to fields mentioned above also `stage, complete, error_message, scratch_url` can be added.

**Comment by FabienTaillon** [comment]
One thing took me quite a while to figure out: on the `deployments` table, `stage` should have a default value of `init` otherwise nothing will happen. I think I'll create a pull request with the script I used, even if it's not 100% accurate it will help everyone running it locally.

**Comment by FabienTaillon** [comment]
@Stefanvdk Have a look to this [pull request](https://github.com/wadewegner/deploy-to-sfdx/pull/33/files?diff=split), you'll get the deployments.sql I used.

Either @wadewegner will use it as a starting point for the correct script, or reject it and update with its own, but it the meantime it will help anyone trying to run the app locally.
