### ISSUE TITLE
The created scratch org cannot be tracted.

### ISSUE THREAD

**Issue by donttrickrick** [wadewegner/deploy-to-sfdx#34]
Hey,

I deployed dreamforce17/purealoe by this tool. It is awesome. Somehow I need to work on purealoe today but the dev hub app doesn't have the login password, or any login button. I try to leverage sfdx cli but it seems cli cannot help if the org isn't created by cli. How can I re-login the scratch org? Please remind me if I missed something. Thank you in advance.

**Comment by FabienTaillon** [comment]
I don’t think you can log again now as it’s not in the CLI. Why not creating a new Scratch Org through this tool and once in just reset your password (and note your login) ? 

Don’t forget that the Scratch Org will only live for 7 days, so if you need to change some stuff in the org you should also pull the code locally. 

Deploy-to-SFDX is a great tool to have a look clickly to an app, but for a dev purpose I would rather git clone the code locally and create a Scratch Org through the CLI.

**Comment by donttrickrick** [comment]
@FabienTaillon Thanks for the comments. I am clear now.

**Comment by wadewegner** [comment]
Thanks @FabienTaillon!

The purpose of this tool is really to help you try things out and test the waters. You can do everything it's doing via the CLI, and then some.
