### ISSUE TITLE
No .salesforcedx.yaml found in repository

### ISSUE THREAD

**Issue by dennisschultz-db** [wadewegner/deploy-to-sfdx#42]
Attempting to deploy from repository https://github.com/dschultz-mo/EventHub but getting the following error:

```
GUID: a5a2b90e-36e0-ba33-ab43-5b867b6fdc7d ERROR: ENOENT: no such file or directory, open 'undefined'.

4) GUID: a5a2b90e-36e0-ba33-ab43-5b867b6fdc7d ERROR: ENOENT: no such file or directory, open 'undefined'.
3) Set instance url to https://dws-legoland-demo-0001.my.salesforce.com.
2) Successfully cloned https://github.com/dschultz-mo/EventHub.
1) No .salesforcedx.yaml found in repository. Using defaults.
```

Not sure what to make of 4), but it is probably caused by 1).  I double-checked several times, but I do think I have a .salesforcedx.yaml file there.  What am I missing, Wade?

**Comment by FabienTaillon** [comment]
Did you just fixed it ?

**Comment by dennisschultz-db** [comment]
Hmmm, it just worked!  I had removed the indentation from my yaml file, but had tried after committing and it still gave me this error.  Now it seems to be working.  I have no explanation.
